name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for getting in touch with us. We will have a look asap into this issue.'
        pr-message: 'Thank you for your contribution. Your PR will be reviewed an you will get feedback asap.'
